#!/bin/bash
red='\e[31m'
green='\e[32m'
blue='\e[34m'
yellow='\e[33m'
NC='\e[0m'
echo -e "\e[36m------------------------------------------\e[0m"
read -p "※ Enter Username To Change : " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
read -p "※ Enter New Password For User $username : " password
  egrep "^$username" /etc/passwd >/dev/null
  echo -e "$password\n$password" | passwd $username
  clear
  echo " ";
	echo " ";
	echo " ";
	echo " ";
	echo -e " \e[36m※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※
 ※                                 ※
 ※ ****************************************
 ※ Program: Auto Installer VPN Server     *
 ※ Developer: Magepanda VPN               *
 ※ Nickname: Choy CND                     *
 ※ FB Page : Alvarisha Official           *
 ※ ****************************************
 ※                                 ※
 ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※\e[0m";
	echo "
 ◎ Details For Your Account ◎";
  echo " ";
  echo -e "  \e[34m※\e[0m Username ID  : ${blue}$username${NC}";
  echo -e "  ${green}※${NC} New Password : ${green}$password${NC}";
  echo " ";
  echo " ♡ ALWAYS SUPPORT KINGKONGVPN™ SERVER ♡";
  echo " ";
  echo " ";
  echo " ";
  echo " ";

else
echo -e "Username ${red}$username${NC} Does Not Exist"
exit 0
fi
