#!/bin/bash
# ****************************************
# Program: Auto Installer VPN Server
# Lock User.
red='\e[31m'
green='\e[32m'
blue='\e[34m'
NC='\e[0m'
echo -e "\e[36m------------------------------------------\e[0m"
read -p "※ Enter Username To Be Lock : " username
egrep "^$username" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
# proses mengganti passwordnya
passwd -l $username
clear
  echo " ";
	echo " ";
	echo " ";
	echo " ";
	echo -e " \e[36m※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※
 ※                                 ※
 ※ ****************************************
 ※ Program: Auto Installer VPN Server     *
 ※ Developer: Magepanda VPN               *
 ※ Nickname: Choy CND                     *
 ※ FB Page : Alvarisha Official           *
 ※ ****************************************
 ※                                 ※
 ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※ ※\e[0m";
	echo "
 ◎ Your Account Status ◎";
  echo " "
  echo -e "  \e[34m※\e[0m Username : ${blue}$username${NC}";
  echo -e "  \e[31m※\e[0m Status   : ${red}LOCKED${NC}";
  echo " ";
  echo " ★ POWER BY KINGKONGVPN™ SERVER ★";
  echo " ";
	echo " ";
	echo " ";
	echo " ";
else
echo "Username ${red}$username${NC} Does Not Exist ..!"
    exit 1
fi
